# Generated by Django 5.2.1 on 2025-06-15 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("room_id", models.CharField(db_index=True, max_length=20)),
                ("player_id", models.CharField(max_length=100)),
                ("player_color", models.CharField(max_length=20)),
                ("display_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("last_ping", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game_state_backup", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["room_id", "is_active"],
                        name="game_sessio_room_id_016c06_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="game_sessio_user_id_8239a7_idx",
                    ),
                ],
                "unique_together": {("room_id", "user")},
            },
        ),
    ]
