# Generated by Django 5.2.1 on 2025-06-02 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Main Board", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "board_states",
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "edge_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("has_road", models.BooleanField(default=False)),
                (
                    "player_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "edges",
                "ordering": ["edge_id"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("dice_distribution", models.JSONField(blank=True, default=dict)),
                ("turns", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "games",
            },
        ),
        migrations.CreateModel(
            name="Vertex",
            fields=[
                (
                    "vertex_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("has_settlement", models.BooleanField(default=False)),
                (
                    "player_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vertices",
                "ordering": ["vertex_id"],
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("victory_points", models.IntegerField()),
                ("roads_built", models.IntegerField(default=0)),
                ("settlements_built", models.IntegerField(default=0)),
                ("cities_built", models.IntegerField(default=0)),
                ("longest_road", models.BooleanField(default=False)),
                ("largest_army", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        db_column="game_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_api.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "game_players",
                "unique_together": {("game", "user")},
            },
        ),
        migrations.CreateModel(
            name="PlayerResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("wood", "Wood"),
                            ("brick", "Brick"),
                            ("sheep", "Sheep"),
                            ("wheat", "Wheat"),
                            ("ore", "Ore"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "game_player",
                    models.ForeignKey(
                        db_column="game_player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_api.gameplayer",
                    ),
                ),
            ],
            options={
                "db_table": "player_resources",
            },
        ),
    ]
